# Generated by Django 6.0.1 on 2026-07-31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import tracker.models.fields
import tracker.zsr_legacy


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0083_merge_0082_add_bid_tags_0082_add_original_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZSRRunMetadata',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('short_name', models.CharField(blank=True, max_length=64)),
                ('layout_prefix', models.CharField(blank=True, max_length=64)),
                ('discord', models.CharField(blank=True, max_length=64)),
                ('commentary_layout', models.CharField(blank=True, max_length=64)),
                ('tracker_mode', models.CharField(blank=True, max_length=64)),
                (
                    'chat_group',
                    models.CharField(blank=True, default='ZSRM', max_length=64),
                ),
                ('show_seeding', models.BooleanField(default=False)),
                ('twitch_game', models.CharField(blank=True, max_length=256)),
                ('twitch_tags', models.JSONField(blank=True, default=list)),
                (
                    'youtube',
                    models.JSONField(
                        blank=True, default=tracker.zsr_legacy.default_youtube_settings
                    ),
                ),
                ('custom_background', models.CharField(blank=True, max_length=64)),
                ('custom_cta', models.CharField(blank=True, max_length=128)),
                ('custom_channels', models.JSONField(blank=True, default=dict)),
                ('race_time', models.DateTimeField(blank=True, null=True)),
                ('timer_notes', models.TextField(blank=True)),
                ('speedrun_com_slug', models.CharField(blank=True, max_length=256)),
                ('round', models.CharField(blank=True, max_length=128)),
                ('qualifier', models.BooleanField(default=False)),
                (
                    'qualifier_race_count',
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    'qualifier_max_races',
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    'max_runner_count',
                    models.PositiveSmallIntegerField(
                        default=4,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ('team_mode', models.BooleanField(default=False)),
                (
                    'team_time',
                    models.CharField(blank=True, default='default', max_length=64),
                ),
                ('use_team_timers', models.BooleanField(default=False)),
                ('hide_timer', models.BooleanField(default=False)),
                (
                    'team_count',
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ('bracket', models.TextField(blank=True)),
                ('data_source', models.CharField(blank=True, max_length=64)),
                (
                    'custom_background_hide_assets',
                    models.BooleanField(default=False),
                ),
                ('logo_overlay', models.CharField(blank=True, max_length=256)),
                (
                    'discord_module',
                    models.CharField(blank=True, default='general', max_length=64),
                ),
                ('tournament_module', models.CharField(blank=True, max_length=64)),
                ('tournament_slug', models.CharField(blank=True, max_length=256)),
                ('hint_list', models.JSONField(blank=True, default=list)),
                ('racetime_bot', models.BooleanField(default=False)),
                (
                    'stats',
                    models.JSONField(
                        blank=True, default=tracker.zsr_legacy.default_stats_settings
                    ),
                ),
                ('title_template', models.TextField(blank=True)),
                ('custom_music', models.CharField(blank=True, max_length=256)),
                ('sniping_check', models.BooleanField(default=False)),
                (
                    'checklist',
                    models.CharField(blank=True, default='default', max_length=64),
                ),
                ('extra_info', models.TextField(blank=True)),
                ('face_cam', models.BooleanField(default=False)),
                (
                    'run',
                    tracker.models.fields.OneToOneOrNoneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='zsr_metadata',
                        to='tracker.speedrun',
                    ),
                ),
            ],
            options={
                'verbose_name': 'ZSR run metadata',
                'verbose_name_plural': 'ZSR run metadata',
            },
        ),
    ]
