# Generated by Django 6.0.8 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0084_zsr_run_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='discord',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
