# Generated by Django 6.0.8 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0085_add_talent_discord'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedrun',
            name='trackers',
            field=models.ManyToManyField(
                blank=True, related_name='tracking', to='tracker.talent'
            ),
        ),
    ]
